---
- name: web server
  hosts: web
  tasks:
    - name: web direcory created
      file:
        path: /home/ec2-user/web-dir
        state: directory
    - name: file download
      get_url:
        url: https://www.dwsamplefiles.com/?dl_id=176
        dest: /home/ec2-user
- name: web server
  hosts: app
  tasks:
    - name: web direcory created
      file:
        path: /home/ec2-user/app-dir
        state: directory
...
